services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  e-commerce-api:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - .:/e-commerce-api
      - staticfiles:/e-commerce-api/staticfiles
    ports:
      - "8000:8000"
   
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=backend
      - DJANGO_DB_USER=backend
      - DJANGO_DB_PASSWORD=backend
      - DJANGO_SECRET_KEY=changeme
      - DJANGO_ALLOWED_HOSTS=*

volumes:
  postgres_data:
  staticfiles:
  redis_data: 
