# Generated by Django 5.2.4 on 2025-07-07
from django.db import migrations, models
import django.db.models.deletion

def create_builtin_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('campaigns', 'EmailTemplate')
    builtins = [
        {
            'name': 'Promotion - Summer Sale',
            'subject': 'YD Bloom Summer Sale! 🌞',
            'content': '<h2>Big Summer Sale!</h2><p>Dear {{ user.get_full_name|default:user.username }},<br>Enjoy up to <b>50% off</b> on selected items. Shop now and save big!</p><a href="https://ydbloom.com/shop" style="background:#4c51bf;color:white;padding:10px 20px;border-radius:5px;text-decoration:none;">Shop Now</a>',
        },
        {
            'name': 'Event - New Collection Launch',
            'subject': 'New Collection Launch at YD Bloom!',
            'content': '<h2>New Collection Just Arrived!</h2><p>Hi {{ user.get_full_name|default:user.username }},<br>We are excited to announce our latest collection. Be the first to explore new arrivals!</p><a href="https://ydbloom.com/new" style="background:#7c3aed;color:white;padding:10px 20px;border-radius:5px;text-decoration:none;">See New Collection</a>',
        },
        {
            'name': 'Discount - Special Offer',
            'subject': 'Special Discount Just for You!',
            'content': '<h2>Exclusive Discount</h2><p>Hello {{ user.get_full_name|default:user.username }},<br>Use code <b>WELCOME10</b> for 10% off your next order. Don\'t miss out!</p><a href="https://ydbloom.com/discount" style="background:#43e97b;color:white;padding:10px 20px;border-radius:5px;text-decoration:none;">Use Discount</a>',
        },
        {
            'name': 'Announcement - Important Update',
            'subject': 'YD Bloom - Important Update',
            'content': '<h2>We Have News!</h2><p>Dear {{ user.get_full_name|default:user.username }},<br>We have an important update for you. Please check your account for details.</p>',
        },
    ]
    for t in builtins:
        EmailTemplate.objects.get_or_create(name=t['name'], defaults={
            'subject': t['subject'],
            'content': t['content'],
            'is_builtin': True,
        })

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content with {{ user.username }} and {{ user.get_full_name }} placeholders')),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in templates cannot be deleted by staff.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='HTML content')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log', models.TextField(blank=True, help_text='Log of send results (optional)')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.emailtemplate')),
            ],
        ),
        migrations.RunPython(create_builtin_templates),
    ] 