# Generated by Django 5.2.4 on 2025-07-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='name',
            field=models.CharField(blank=True, help_text='Internal campaign name', max_length=100, null=True),
        ),
    ]
