# Generated by Django 5.2.4 on 2025-07-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emailcampaign_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='body',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='subject',
        ),
    ]
