# Generated by Django 5.2.4 on 2025-07-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_emailtemplate_emailcampaign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCampaign',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
